apiVersion: v1
kind: Pod
metadata:
  name: job-with-sidecar
spec:
  restartPolicy: Never
  initContainers:
  - name: sidecar-logger
    image: busybox
    restartPolicy: Always
    command: ["sh", "-c", "while true; do echo sidecar running; sleep 5; done"]
  containers:
  - name: main-job
    image: busybox
    command: ["sh", "-c", "echo job logic; sleep 10"]