apiVersion: v1
kind: Pod
metadata:
  name: secure-override-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      capabilities:
        add:
        - SYS_TIME