apiVersion: v1
kind: Pod
metadata:
  name: tolerant-pod
spec:
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "reserved"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx