apiVersion: apps/v1
kind: Deployment
metadata:
  name: example2-svc-app
  labels:
    app: example2-svc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example2-svc-app
  template:
    metadata:
      labels:
        app: example2-svc-app
    spec:
      containers:
      - name: main-app
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: example2-svc-app
  labels:
    app: example2-svc-app
spec:
  selector:
    app: example2-svc-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
