apiVersion: v1
kind: Secret
metadata:
  name: app-creds
  namespace: default
type: Opaque
data:
  # The following are environment variables
  DB_HOST: bXlzcWwtc2VydmljZQ==
  DB_USER: cm9vdA==
  DB_PASSWORD: VDBwU2VjcmV0