apiVersion: v1
kind: Pod
metadata:
  name: pod-map-secret-ref
  labels:
    app: pod-map-secret-ref
  namespace: default
spec:
  containers:
    - name: app
      image: josefloressv/flask_mysql_app
      envFrom:
        - secretRef:
            name: app-creds

---
apiVersion: v1
kind: Service
metadata:
  name: service-pod-map-secret-ref
  namespace: default
spec:
  selector:
    app: pod-map-secret-ref
  ports:
  - port: 8081
    targetPort: 5000
