apiVersion: v1
kind: Pod
metadata:
  name: pod-map-secret-keys
  labels:
    app: pod-map-secret-keys
  namespace: default
spec:
  containers:
    - name: app
      image: josefloressv/flask_mysql_app
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-creds
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-creds
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-creds
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: service-pod-map-secret-keys
  namespace: default
spec:
  selector:
    app: pod-map-secret-keys
  ports:
  - port: 8082
    targetPort: 5000